### ISSUE TITLE
How to setup notification code for couple devices?

### ISSUE THREAD

**Issue by stefunkk** [Bartvelp/pushme#1]
Hello,

Is it possible to setup notification for couple devices? I can't find option on the page

**Comment by stefunkk** [comment]
btw. I love the simplicity of the project, great work! :)

**Comment by Bartvelp** [comment]
Hi @stefunkk ,
Yes you can request as many notification codes as you like, each code is bound to a specific device (or rather the browser on that device). You cannot link multiple devices to one code if that is what you mean.
If you want to notify multiple devices at the same time, simply loop through the device codes and send a request for each one to https://pushme.now.sh/api/sendNotification

Can I maybe ask how you stumbled upon my repo? I never actually had anyone interact with them some I am a bit curious.

**Comment by stefunkk** [comment]
I googled simple solutions for notifications on esp and come across discussion on reddit, and here i am :)

**Comment by Bartvelp** [comment]
That's cool, if you have any other questions lmk.
